### PR TITLE
Feature/test mocking

### PR DESCRIPTION
**Pull request by tenorz007**
So I was finally able to come around to mocking all external API calls.
When you run the tests now, they are way much faster as they don't have to make any external calls.

PS: I also came across a few bugs in the code.

### CODE REVIEW

**Comment by prodicus** [comment]
Hey @tenorz007 . Good to see you back 😄 

I am not too familiar with the `mocks` framework. Will have to check this PR out later today/tomorrow. Any good resource to go through?

Also, I see you mentioned you found some bugs. Would be great if you could point them out for the brevity in this thread.

And again, thanks for contributing 👍 

Cheers

**Comment by tenorz007** [comment]
[https://docs.python.org/2/library/unittest.html](Python 2 Docs)
[https://realpython.com/blog/python/testing-third-party-apis-with-mocks/](blog)

**Comment by prodicus** [comment]
@tenorz007 Going through them. Would it be ok for you to join our gitter channel. Had some questions which if put on this PR thread would spam the whole watchers list. Here is the link for the channel. [https://gitter.im/prodicus/vocabulary](https://gitter.im/prodicus/vocabulary) Ping me there if you join it

Cheers!

**Comment by prodicus** [comment]
@tenorz007  I was wondering whether we should also add some test(s) which hit the real server.
I mean if the data on their end changes at some point. The parsing would break basically testing our mocked data response to what the response the API server is returning to us,

What are your thoughts on it?

**Comment by prodicus** [comment]
Also, showing test coverage would be a great thing too if possible

**Comment by tenorz007** [comment]
Yeah coverage would be a good addition, so you can actually see how much of the code is being tested.

**Pull request merged**
