### PR TITLE
Fix inconsistent data

### PR DESCRIPTION
**Pull request by tenorz007**
Fix for #27

### CODE REVIEW

**Comment by tenorz007** [comment]
Before
```python
>>> vb.pronunciation("hippopotamus")
[{"rawType": "ahd-legacy", "raw": "hip", "seq": 0}, {"rawType": "arpabet", "raw": "HH IH2 P AH0 P AA1 T AH0 M AH0 S", "seq": 0}]
>>> vb.part_of_speech("hello")
[{"text": "interjection", "example": "greeting", "seq": 0}]
>>> vb.antonym("hate")
{"text": ["hate"]}
```
Now
```python
>>> vb.pronunciation("hippopotamus")
[{"rawType": "ahd-legacy", "raw": "hip", "seq": 0}, {"rawType": "arpabet", "raw": "HH IH2 P AH0 P AA1 T AH0 M AH0 S", "seq": 1}]
>>> vb.part_of_speech("hello")
[{"text": "interjection", "example": "greeting", "seq": 0}, {"text": "verb-intransitive", "example": "To call.", "seq": 1}]
>>> vb.antonym("hate")
[{"text": "hate", "seq": 0}, {"text": "dislike", "seq": 1}, {"text": "hater", "seq": 2}]
```

**Comment by prodicus** [comment]
@tenorz007 Awesome. 👍 Could you update the relevant docs for this? Or should I merge it before?

**Comment by tenorz007** [comment]
I would update the docs first.
Does this mean a new release? I was suggesting semantic version which would streamline release changes?

**Comment by prodicus** [comment]
@tenorz007 

>I would update the docs first.
Cool. Please push the updated docs then. Will merge it.

>Does this mean a new release?
Yes, I think this is eligible for a version bump. Updating that too would be one of the agendas of this PR then

>I was suggesting semantic version which would streamline release changes?
I thought we were already using semantic versioning weren't we? Point me out if I am mistaken here

**Comment by tenorz007** [comment]
@prodicus In a way yes, but ideally it should be of the format major:minor:patch {*}
From what I understand:
* major is updated when it could break existing functionality no backward compatibility possibly
* minor is updated for new features basically
* patch is updated for things like bug fixes

**Comment by prodicus** [comment]
@tenorz007 Yup. Was under a wrong notion then. Time for our first `1.0.0` then? 😄 ?

**Comment by tenorz007** [comment]
@prodicus Well if you feel it's stable enough

**Pull request merged**
